name: Learn Buid-Depoy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Buid And Deploy Learn
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js env
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependecies
        run: npm install

      - name: Unit Test
        run: npm test

      - name: Build And Deploy Package
        run: npm run build

      - name: Build Docker Images
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerFile: DockerFile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME}}/learn-cicd:$(date-'%Y-%m-%d%H-%M-%S')

      - name: Login To Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Dockerhub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: DockerFile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME}}/learn-cicd:$(date-'%Y-%m-%d%H-%M-%S')
